PREFIX	= /usr/local
DESTDIR	=
MKDIR	= mkdir -m 0755 -p
INSTALL	= install
RM	= rm -f


all:

clean:

distclean: clean

install:
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 -- fpdf.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/fpdf.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 -- font/courier.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/courier.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 -- font/courierb.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/courierb.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 -- font/courierbi.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/courierbi.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 -- font/courieri.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/courieri.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 -- font/helvetica.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/helvetica.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 -- font/helveticab.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/helveticab.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 -- font/helveticabi.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/helveticabi.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 -- font/helveticai.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/helveticai.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 -- font/symbol.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/symbol.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 -- font/times.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/times.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 -- font/timesb.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/timesb.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 -- font/timesbi.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/timesbi.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 -- font/timesi.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/timesi.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 -- font/zapfdingbats.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/zapfdingbats.php

uninstall:
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/fpdf.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/courier.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/courierb.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/courierbi.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/courieri.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/helvetica.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/helveticab.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/helveticabi.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/helveticai.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/symbol.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/times.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/timesb.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/timesbi.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/timesi.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/font/zapfdingbats.php

.PHONY: all clean distclean install uninstall
