PREFIX	= /usr/local
DESTDIR	=
MKDIR	= mkdir -m 0755 -p
INSTALL	= install
RM	= rm -f


all:

clean:

distclean: clean

install:
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 courier.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/courier.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 courierb.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/courierb.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 courierbi.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/courierbi.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 courieri.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/courieri.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 helvetica.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/helvetica.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 helveticab.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/helveticab.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 helveticabi.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/helveticabi.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 helveticai.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/helveticai.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 symbol.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/symbol.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 times.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/times.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 timesb.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/timesb.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 timesbi.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/timesbi.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 timesi.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/timesi.php
	$(MKDIR) $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf
	$(INSTALL) -m 0644 zapfdingbats.php $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/zapfdingbats.php

uninstall:
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/courier.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/courierb.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/courierbi.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/courieri.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/helvetica.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/helveticab.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/helveticabi.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/helveticai.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/symbol.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/times.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/timesb.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/timesbi.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/timesi.php
	$(RM) -- $(DESTDIR)$(PREFIX)/daportal/src/formats/fpdf/zapfdingbats.php

.PHONY: all clean distclean install uninstall
